// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/engine/distributed_execution/querierpb/querier.proto

package querierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FragmentID    uint64                 `protobuf:"varint,1,opt,name=fragmentID,proto3" json:"fragmentID,omitempty"`
	Batchsize     int64                  `protobuf:"varint,2,opt,name=batchsize,proto3" json:"batchsize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesRequest) Reset() {
	*x = SeriesRequest{}
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesRequest) ProtoMessage() {}

func (x *SeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesRequest.ProtoReflect.Descriptor instead.
func (*SeriesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescGZIP(), []int{0}
}

func (x *SeriesRequest) GetFragmentID() uint64 {
	if x != nil {
		return x.FragmentID
	}
	return 0
}

func (x *SeriesRequest) GetBatchsize() int64 {
	if x != nil {
		return x.Batchsize
	}
	return 0
}

type NextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FragmentID    uint64                 `protobuf:"varint,1,opt,name=fragmentID,proto3" json:"fragmentID,omitempty"`
	Batchsize     int64                  `protobuf:"varint,2,opt,name=batchsize,proto3" json:"batchsize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRequest) Reset() {
	*x = NextRequest{}
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRequest) ProtoMessage() {}

func (x *NextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRequest.ProtoReflect.Descriptor instead.
func (*NextRequest) Descriptor() ([]byte, []int) {
	return file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescGZIP(), []int{1}
}

func (x *NextRequest) GetFragmentID() uint64 {
	if x != nil {
		return x.FragmentID
	}
	return 0
}

func (x *NextRequest) GetBatchsize() int64 {
	if x != nil {
		return x.Batchsize
	}
	return 0
}

type OneSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneSeries) Reset() {
	*x = OneSeries{}
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneSeries) ProtoMessage() {}

func (x *OneSeries) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneSeries.ProtoReflect.Descriptor instead.
func (*OneSeries) Descriptor() ([]byte, []int) {
	return file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescGZIP(), []int{2}
}

func (x *OneSeries) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type StepVectorBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepVectors   []*StepVector          `protobuf:"bytes,1,rep,name=step_vectors,json=stepVectors,proto3" json:"step_vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepVectorBatch) Reset() {
	*x = StepVectorBatch{}
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepVectorBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepVectorBatch) ProtoMessage() {}

func (x *StepVectorBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepVectorBatch.ProtoReflect.Descriptor instead.
func (*StepVectorBatch) Descriptor() ([]byte, []int) {
	return file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescGZIP(), []int{3}
}

func (x *StepVectorBatch) GetStepVectors() []*StepVector {
	if x != nil {
		return x.StepVectors
	}
	return nil
}

type StepVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	Sample_IDs    []uint64               `protobuf:"varint,2,rep,packed,name=sample_IDs,json=sampleIDs,proto3" json:"sample_IDs,omitempty"`
	Samples       []float64              `protobuf:"fixed64,3,rep,packed,name=samples,proto3" json:"samples,omitempty"`
	Histogram_IDs []uint64               `protobuf:"varint,4,rep,packed,name=histogram_IDs,json=histogramIDs,proto3" json:"histogram_IDs,omitempty"`
	Histograms    []*FloatHistogram      `protobuf:"bytes,5,rep,name=histograms,proto3" json:"histograms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepVector) Reset() {
	*x = StepVector{}
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepVector) ProtoMessage() {}

func (x *StepVector) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepVector.ProtoReflect.Descriptor instead.
func (*StepVector) Descriptor() ([]byte, []int) {
	return file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescGZIP(), []int{4}
}

func (x *StepVector) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *StepVector) GetSample_IDs() []uint64 {
	if x != nil {
		return x.Sample_IDs
	}
	return nil
}

func (x *StepVector) GetSamples() []float64 {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *StepVector) GetHistogram_IDs() []uint64 {
	if x != nil {
		return x.Histogram_IDs
	}
	return nil
}

func (x *StepVector) GetHistograms() []*FloatHistogram {
	if x != nil {
		return x.Histograms
	}
	return nil
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescGZIP(), []int{5}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FloatHistogram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatHistogram) Reset() {
	*x = FloatHistogram{}
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatHistogram) ProtoMessage() {}

func (x *FloatHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatHistogram.ProtoReflect.Descriptor instead.
func (*FloatHistogram) Descriptor() ([]byte, []int) {
	return file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescGZIP(), []int{6}
}

var File_pkg_engine_distributed_execution_querierpb_querier_proto protoreflect.FileDescriptor

const file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDesc = "" +
	"\n" +
	"8pkg/engine/distributed_execution/querierpb/querier.proto\x12\tquerierpb\"M\n" +
	"\rSeriesRequest\x12\x1e\n" +
	"\n" +
	"fragmentID\x18\x01 \x01(\x04R\n" +
	"fragmentID\x12\x1c\n" +
	"\tbatchsize\x18\x02 \x01(\x03R\tbatchsize\"K\n" +
	"\vNextRequest\x12\x1e\n" +
	"\n" +
	"fragmentID\x18\x01 \x01(\x04R\n" +
	"fragmentID\x12\x1c\n" +
	"\tbatchsize\x18\x02 \x01(\x03R\tbatchsize\"5\n" +
	"\tOneSeries\x12(\n" +
	"\x06labels\x18\x01 \x03(\v2\x10.querierpb.LabelR\x06labels\"K\n" +
	"\x0fStepVectorBatch\x128\n" +
	"\fstep_vectors\x18\x01 \x03(\v2\x15.querierpb.StepVectorR\vstepVectors\"\xb3\x01\n" +
	"\n" +
	"StepVector\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\x1d\n" +
	"\n" +
	"sample_IDs\x18\x02 \x03(\x04R\tsampleIDs\x12\x18\n" +
	"\asamples\x18\x03 \x03(\x01R\asamples\x12#\n" +
	"\rhistogram_IDs\x18\x04 \x03(\x04R\fhistogramIDs\x129\n" +
	"\n" +
	"histograms\x18\x05 \x03(\v2\x19.querierpb.FloatHistogramR\n" +
	"histograms\"1\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x10\n" +
	"\x0eFloatHistogram2\x8b\x01\n" +
	"\vQueryServer\x12<\n" +
	"\x06Series\x12\x18.querierpb.SeriesRequest\x1a\x14.querierpb.OneSeries\"\x000\x01\x12>\n" +
	"\x04Next\x12\x16.querierpb.NextRequest\x1a\x1a.querierpb.StepVectorBatch\"\x000\x01BLZJgithub.com/cortexproject/cortex/pkg/engine/distributed_execution/querierpbb\x06proto3"

var (
	file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescOnce sync.Once
	file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescData []byte
)

func file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescGZIP() []byte {
	file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescOnce.Do(func() {
		file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDesc), len(file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDesc)))
	})
	return file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDescData
}

var file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_engine_distributed_execution_querierpb_querier_proto_goTypes = []any{
	(*SeriesRequest)(nil),   // 0: querierpb.SeriesRequest
	(*NextRequest)(nil),     // 1: querierpb.NextRequest
	(*OneSeries)(nil),       // 2: querierpb.OneSeries
	(*StepVectorBatch)(nil), // 3: querierpb.StepVectorBatch
	(*StepVector)(nil),      // 4: querierpb.StepVector
	(*Label)(nil),           // 5: querierpb.Label
	(*FloatHistogram)(nil),  // 6: querierpb.FloatHistogram
}
var file_pkg_engine_distributed_execution_querierpb_querier_proto_depIdxs = []int32{
	5, // 0: querierpb.OneSeries.labels:type_name -> querierpb.Label
	4, // 1: querierpb.StepVectorBatch.step_vectors:type_name -> querierpb.StepVector
	6, // 2: querierpb.StepVector.histograms:type_name -> querierpb.FloatHistogram
	0, // 3: querierpb.QueryServer.Series:input_type -> querierpb.SeriesRequest
	1, // 4: querierpb.QueryServer.Next:input_type -> querierpb.NextRequest
	2, // 5: querierpb.QueryServer.Series:output_type -> querierpb.OneSeries
	3, // 6: querierpb.QueryServer.Next:output_type -> querierpb.StepVectorBatch
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_engine_distributed_execution_querierpb_querier_proto_init() }
func file_pkg_engine_distributed_execution_querierpb_querier_proto_init() {
	if File_pkg_engine_distributed_execution_querierpb_querier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDesc), len(file_pkg_engine_distributed_execution_querierpb_querier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_engine_distributed_execution_querierpb_querier_proto_goTypes,
		DependencyIndexes: file_pkg_engine_distributed_execution_querierpb_querier_proto_depIdxs,
		MessageInfos:      file_pkg_engine_distributed_execution_querierpb_querier_proto_msgTypes,
	}.Build()
	File_pkg_engine_distributed_execution_querierpb_querier_proto = out.File
	file_pkg_engine_distributed_execution_querierpb_querier_proto_goTypes = nil
	file_pkg_engine_distributed_execution_querierpb_querier_proto_depIdxs = nil
}
